const menu = {
    list() {
        return [
    {
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"革命先辈类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryGemingxianbei"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"历程时期管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryGuanghuilicheng"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"成就类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryHuihuangchengjiu"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"几大会议管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryLijiehuiyi"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"每日资讯类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryZixun"
                    }
                ],
                "menu":"基础数据管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"革命先辈管理",
                        "menuJump":"列表",
                        "tableName":"gemingxianbei"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"革命先辈留言管理",
                        "menuJump":"列表",
                        "tableName":"gemingxianbeiLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"革命先辈收藏管理",
                        "menuJump":"列表",
                        "tableName":"gemingxianbeiCollection"
                    }
                ],
                "menu":"革命先辈管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"光辉历程管理",
                        "menuJump":"列表",
                        "tableName":"guanghuilicheng"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"光辉历程留言管理",
                        "menuJump":"列表",
                        "tableName":"guanghuilichengLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"光辉历程收藏管理",
                        "menuJump":"列表",
                        "tableName":"guanghuilichengCollection"
                    }
                ],
                "menu":"光辉历程管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"辉煌成就管理",
                        "menuJump":"列表",
                        "tableName":"huihuangchengjiu"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"辉煌成就留言管理",
                        "menuJump":"列表",
                        "tableName":"huihuangchengjiuLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"辉煌成就收藏管理",
                        "menuJump":"列表",
                        "tableName":"huihuangchengjiuCollection"
                    }
                ],
                "menu":"辉煌成就管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"历届会议管理",
                        "menuJump":"列表",
                        "tableName":"lijiehuiyi"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"历届会议留言管理",
                        "menuJump":"列表",
                        "tableName":"lijiehuiyiLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"历届会议收藏管理",
                        "menuJump":"列表",
                        "tableName":"lijiehuiyiCollection"
                    }
                ],
                "menu":"历届会议管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"留言板管理",
                        "menuJump":"列表",
                        "tableName":"liuyan"
                    }
                ],
                "menu":"留言板管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"单页数据管理",
                        "menuJump":"列表",
                        "tableName":"singleSeach"
                    }
                ],
                "menu":"单页数据管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"用户管理",
                        "menuJump":"列表",
                        "tableName":"yonghu"
                    }
                ],
                "menu":"用户管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"每日资讯管理",
                        "menuJump":"列表",
                        "tableName":"zixun"
                    }
                ],
                "menu":"每日资讯管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"轮播图管理",
                        "menuJump":"列表",
                        "tableName":"config"
                    }
                ],
                "menu":"轮播图信息"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"管理员",
        "tableName":"users"
    }
	,
	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"革命先辈管理",
                        "menuJump":"列表",
                        "tableName":"gemingxianbei"
                    }
                    ,
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"革命先辈留言管理",
                        "menuJump":"列表",
                        "tableName":"gemingxianbeiLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"革命先辈收藏管理",
                        "menuJump":"列表",
                        "tableName":"gemingxianbeiCollection"
                    }
                ],
                "menu":"革命先辈管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"光辉历程管理",
                        "menuJump":"列表",
                        "tableName":"guanghuilicheng"
                    }
                    ,
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"光辉历程留言管理",
                        "menuJump":"列表",
                        "tableName":"guanghuilichengLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"光辉历程收藏管理",
                        "menuJump":"列表",
                        "tableName":"guanghuilichengCollection"
                    }
                ],
                "menu":"光辉历程管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"辉煌成就管理",
                        "menuJump":"列表",
                        "tableName":"huihuangchengjiu"
                    }
                    ,
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"辉煌成就留言管理",
                        "menuJump":"列表",
                        "tableName":"huihuangchengjiuLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"辉煌成就收藏管理",
                        "menuJump":"列表",
                        "tableName":"huihuangchengjiuCollection"
                    }
                ],
                "menu":"辉煌成就管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"历届会议管理",
                        "menuJump":"列表",
                        "tableName":"lijiehuiyi"
                    }
                    ,
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"历届会议留言管理",
                        "menuJump":"列表",
                        "tableName":"lijiehuiyiLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"历届会议收藏管理",
                        "menuJump":"列表",
                        "tableName":"lijiehuiyiCollection"
                    }
                ],
                "menu":"历届会议管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"留言板管理",
                        "menuJump":"列表",
                        "tableName":"liuyan"
                    }
                ],
                "menu":"留言板管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"每日资讯管理",
                        "menuJump":"列表",
                        "tableName":"zixun"
                    }
                ],
                "menu":"每日资讯管理"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"用户",
        "tableName":"yonghu"
    }
]
    }
}
export default menu;
